# clean_analyze_outbreak_dplyr.R
# Purpose: Clean synthetic CDSC New Year's party outbreak line list using dplyr-style code,
#          produce summary stats, calculate odds ratios per meal, and save basic outputs.
# Author: Generated by M365 Copilot

# ---- Load packages ----

  library(tidyverse)
  library(skimr)
  library(odbc)
  library(zoo)


# ---- Read data ----
linelist <- read_csv("cdsc_new_year_outbreak_linelist.csv", show_col_types = FALSE)

# Exposure event datetime (assumed)
party_dt <- ymd_hm("2026-01-01 20:00", tz = "UTC")

# ---- Standardize booleans & gender (inline with dplyr) ----
true_set  <- c("true","t","1","yes","y")
false_set <- c("false","f","0","no","n")

linelist <- linelist %>%
  mutate(
    # Gender
    gender_std = case_when(
      str_to_lower(str_trim(gender)) %in% c("male","m","man","1","boy") ~ "Male",
      str_to_lower(str_trim(gender)) %in% c("female","f","fem","woman","2","girl") ~ "Female",
      str_trim(gender) == "" ~ NA_character_,
      TRUE ~ "Other"
    ),

    # Symptoms (make logicals)
    sick_std = case_when(str_to_lower(as.character(sick)) %in% true_set ~ TRUE,
                         str_to_lower(as.character(sick)) %in% false_set ~ FALSE,
                         TRUE ~ NA),
    diarrhoea = case_when(str_to_lower(as.character(diorpha)) %in% true_set ~ TRUE,
                          str_to_lower(as.character(diorpha)) %in% false_set ~ FALSE,
                          TRUE ~ NA),
    abdominal_pain_std = case_when(str_to_lower(as.character(abdominal_pain)) %in% true_set ~ TRUE,
                                   str_to_lower(as.character(abdominal_pain)) %in% false_set ~ FALSE,
                                   TRUE ~ NA),
    headache_std = case_when(str_to_lower(as.character(headache)) %in% true_set ~ TRUE,
                             str_to_lower(as.character(headache)) %in% false_set ~ FALSE,
                             TRUE ~ NA),
    fatigue_std = case_when(str_to_lower(as.character(fatigue)) %in% true_set ~ TRUE,
                            str_to_lower(as.character(fatigue)) %in% false_set ~ FALSE,
                            TRUE ~ NA)
  )

# Meal items -> logical
meal_items <- c("prawn_cocktail","roast_turkey","beef_wellington","vegan_lasagne","cheesecake","coleslaw")

linelist <- linelist %>%
  mutate(across(all_of(meal_items), ~ case_when(
    str_to_lower(as.character(.x)) %in% true_set  ~ TRUE,
    str_to_lower(as.character(.x)) %in% false_set ~ FALSE,
    TRUE ~ NA
  ), .names = "{.col}_std"))

# ---- Parse onset and fix years if outside 2025-2026 ----
linelist <- linelist %>%
  mutate(
    symptom_onset_parsed = as_date(symptom_onset, tz = "UTC"),
    onset_year = year(symptom_onset_parsed),
    symptom_onset_dt = case_when(
      is.na(symptom_onset_parsed) ~ NA_POSIXct_,
      onset_year < 2025 | onset_year > 2026 ~ update(symptom_onset_parsed, year = 2026),
      TRUE ~ symptom_onset_parsed
    ),
    hours_since_party = as.numeric(difftime(symptom_onset, party_dt, units = "hours"))
  )

# ---- Age & data quality flags ----
linelist <- linelist %>%
  mutate(
    date_of_birth = ymd(date_of_birth),
    age = as.integer(floor(as.numeric(difftime(as_date("2026-01-01"), date_of_birth, units = "days")) / 365.25)),
    age_flag = age < 10 | age > 100,
    id_flag = is.na(id) | duplicated(id),
    onset_before_party_flag = !is.na(hours_since_party) & hours_since_party < 0
  )

# ---- Case definition ----
linelist <- linelist %>%
  mutate(
    any_symptom = sick_std | diarrhoea,
    case = any_symptom & !is.na(hours_since_party) & hours_since_party >= 0 & hours_since_party <= 24
  )

# ---- Summary statistics ----
summary_stats_simple <- tibble(
  Records = nrow(linelist),
  Cases = sum(linelist$case, na.rm = TRUE),
  Attack_rate = round(sum(linelist$case, na.rm = TRUE) / nrow(linelist), 3),
  ID_issues = sum(linelist$id_flag, na.rm = TRUE),
  Age_issues = sum(linelist$age_flag, na.rm = TRUE),
  Onset_before_party = sum(linelist$onset_before_party_flag, na.rm = TRUE)
)
print("=== Summary Statistics ===")
print(summary_stats_simple)
print("Gender counts:")
print(table(linelist$gender_std, useNA = "ifany"))

# ---- Epidemic curve ----
# Save a simple histogram of hours since party for cases
epicurve <- linelist %>%
  filter(case, !is.na(hours_since_party), hours_since_party >= 0, hours_since_party <= 144) %>%
  ggplot(aes(x = hours_since_party)) +
  geom_histogram(binwidth = 6, fill = "#2c7fb8", color = "white") +
  labs(title = "Epidemic curve: Hours since party (cases)",
       x = "Hours since party", y = "Frequency") +
  theme_minimal()

ggsave("epicurve_hours.png", epicurve, width = 9, height = 5, dpi = 144)

# ---- Odds ratios per meal (Fisher's exact), tidy approach ----
meal_std_cols <- paste0(meal_items, "_std")

or_table <- linelist %>%
  select(case, all_of(meal_std_cols)) %>%
  pivot_longer(cols = all_of(meal_std_cols), names_to = "meal", values_to = "exposed") %>%
  group_by(meal) %>%
  summarise(
    a = sum(exposed == TRUE & case == TRUE, na.rm = TRUE),   # exposed & case
    b = sum(exposed == TRUE & case == FALSE, na.rm = TRUE),  # exposed & noncase
    c = sum(exposed == FALSE & case == TRUE, na.rm = TRUE),  # unexposed & case
    d = sum(exposed == FALSE & case == FALSE, na.rm = TRUE), # unexposed & noncase
    .groups = "drop"
  ) %>%
  rowwise() %>%
  mutate(
    ft = list(suppressWarnings(fisher.test(matrix(c(a,b,c,d), nrow = 2, byrow = TRUE)))),
    OR = as.numeric(ft$estimate),
    CI_low = ft$conf.int[1],
    CI_high = ft$conf.int[2],
    p_value = ft$p.value
  ) %>%
  ungroup() %>%
  select(meal, OR, CI_low, CI_high, p_value, a, b, c, d) %>%
  arrange(desc(OR))

print("=== Odds Ratios by Meal ===")
print(or_table)

write_csv(or_table, "meal_odds_ratios_dplyr.csv")

# Save a cleaned snapshot (minimal columns)
clean_snapshot <- linelist %>%
  select(id, name, date_of_birth, gender_std, age, case, hours_since_party, all_of(meal_std_cols))

write_csv(clean_snapshot, "linelist_clean_snapshot_dplyr.csv")

print("Jana")
